### ISSUE TITLE
Implement Omniauth for  Google Authentication.

### ISSUE THREAD

**Issue by itcharlie** [itcharlie/SquadTeam#1]
There is alot of great examples for this implementation online. Take for example the following source:
https://richonrails.com/articles/google-authentication-in-ruby-on-rails

Bonus points for Twitter and Facebook.
http://sourcey.com/rails-4-omniauth-using-devise-with-twitter-facebook-and-linkedin/

**Comment by itcharlie** [comment]
@GuillermoNeira  I created a branch for you to work on.  ( https://github.com/itcharlie/SquadTeam/tree/Omni_auth_guillermo )

Since you have a local master branch, the way you can push your changes to this remote branch is by running the following command in your terminal :

$ git push origin master:Omni_auth_guillermo

Please let me know if you have any questions.  I already pushed my changes to ( https://github.com/itcharlie/SquadTeam/tree/Omni_auth_charlie ) which should be similar to your work from following the example page on omniauth.

**Comment by GuillermoNeira** [comment]
My changes were push please reference #5
